---
title: "Kaiyo Warehouse Traffic"
author: "Mariel Pacada"
date: "5/15/2020"
output: pdf_document
---

```{r library setup, warning = FALSE}
library(dplyr)
library(ggplot2)
```

```{r data cleaning}
setwd("/Users/marielpacada/kaiyo-traffic")
categories <- read.csv("categories.csv") 
warehouse <- read.csv("warehouse_flux.csv", stringsAsFactors = FALSE)

# remove duplicates 
warehouse$X <- NULL
warehouse <- unique(warehouse)

# join warehouse data with item categories
names(categories)[1] <- "category_id"
warehouse <- merge(warehouse, categories, by = "category_id")
warehouse$category_id <- NULL

# order by timestamp
warehouse$create_date <- strptime(warehouse$create_date, format = "%Y-%m-%d %H:%M:%S")
warehouse <- warehouse[order(warehouse$create_date),]

# parse month and year from timestamp + delete timestamp
warehouse$year <- as.factor(warehouse$create_date$year + 1900)
warehouse$month <- warehouse$create_date$mon + 1
warehouse$month <- month.abb[warehouse$month]
warehouse$create_date <- NULL
```

```{r explore-status}
# which category is highest selling?
sold_data <- warehouse %>% 
               filter(status == "Sold")
ggplot(sold_data, aes(x = category)) + geom_bar(fill = "#F2AE0F") + labs(title = "Sold")

# which _datacategory do we see most of?
receiving_data <- warehouse %>%
                    filter(status == "Receiving")
ggplot(receiving_data, aes(category)) + geom_bar(fill = "#F2AE0F") + labs(title = "Receiving")

# which category is most retired?
retired_data <- warehouse %>% 
                  filter(status == "Retired")
ggplot(retired_data, aes(category)) + geom_bar(fill = "#F2AE0F") + labs(title= "Retired")
```

```{r explore-month, fig.width = 5}
month_data <- warehouse %>% 
                filter(status == "Sold" | status == "Receiving")

ggplot(month_data, aes(x = factor(month, levels = month.abb), fill = status)) + geom_bar(position = position_dodge()) + labs(title = "Activity per month") +
theme(legend.title = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "grey")) +
scale_fill_brewer(palette="GnBu")

# THE FIRST TRIMESTER -- CHECK WHICH CATEGORY OF ITEMS IS RECEIVING THE MOST -- SUGGEST THAT YOU COULD BE MORE SELECTIVE ABOUT THIS -- AND THEN RELATE THIS WITH RETIRED RATIO
```

```{r first-trimester}
first_tri <- warehouse %>% 
               filter(month == "Jan"|month == "Feb"|month == "Mar") %>% 
               filter(status == "Receiving") %>% 
               group_by(category) %>% 
               summarize(count = n())

ggplot(first_tri, aes(x = category, y = count)) + geom_bar(fill = "#43ad26", stat = "identity") + labs(title = "First Trimester Receiving")

```

```{r likelihood-sold}
sold_count_data <- sold_data %>%
                     group_by(category) %>% 
                     summarize(count = n())

receiving_count_data <- receiving_data %>% 
                          group_by(category) %>% 
                          summarize(count = n())

sold_ratio_data <- data.frame(
  category = levels(categories$category),
  sold_ratio = sold_count_data$count / receiving_count_data$count
)

ggplot(sold_ratio_data, aes(x = category, y = sold_ratio)) + geom_bar(fill = "#F2AE0F", stat = "identity") + labs(title = "Sold Ratio") 

# more people are probably buying decor because it is cheaper and a lower commitment 
```

```{r likelihood-retired}
retired_count_data <- retired_data %>%
                        group_by(category) %>% 
                        summarize(count = n())

retired_ratio_data <- data.frame(
  category = levels(categories$category),
  retired_ratio = retired_count_data$count / receiving_count_data$count
)

ggplot(retired_ratio_data, aes(x = category, y = retired_ratio)) + geom_bar(fill = "#F2AE0F", stat = "identity") + labs(title = "Retired Ratio")

```

```{r covid-analysis}
third_of_year <- warehouse %>% 
                   filter(month == "Jan"|month == "Feb"|month == "Mar"|month == "Apr") %>%
                   filter(year == "2018"|year == "2019"|year == "2020")

# this should be two-thirds of the third_of_year data
pre_covid <- third_of_year %>% 
               filter(year != "2020")

# this should be one-third of the third-_of_year_data
covid <- third_of_year %>% 
           filter(year == "2020")

```

```{r covid-ratios}
quad_activity <- function(activity) { 
  total <- length(third_of_year$status[third_of_year$status == activity])
  before <- length(pre_covid$status[pre_covid$status == activity])
  during <- length(covid$status[covid$status == activity])
  
  return(c(total, before, during))
}

sales <- quad_activity("Sold")
rec <- quad_activity("Receiving")

# this is two-thirds :) 
pre_covid_sales <- sales[2] / sales[1]
covid_sales <- sales[3] / sales[1]

# this actually suggests that the covid receiving is higher (should be 1/3 but is 1/2)
# possibly because people are moving out of tri-state area 
pre_covid_rec <- rec[2] / rec[1]
covid_rec <- rec[3] / rec[1]


pre_covid_sales
covid_sales
pre_covid_rec
covid_rec
```

```{r seed-funding-analysis}
# baseline 2018 and 2019 data
general_activity <- warehouse %>% 
                      filter(year != "2020") %>% 
                      group_by(year, status) %>% 
                      summarise(count = n())

general_yearly <- general_activity %>% 
                    group_by(year) %>% 
                    summarize(count = sum(count))

activity_yearly <- function(activity) {
  data <- general_activity %>%
            filter(status == activity)
  return(data)
}

# grew by nearly 75% 
receive_yearly <- activity_yearly("Receiving")

# not selling as much :( 
sold_yearly <- activity_yearly("Sold")

# increase by 40%
retire_yearly <- activity_yearly("Retired")
```

```{r re-enter-activity}
# some items are classified as two different categories!!!
all_received <- receiving_data %>% dplyr::select(status, subitem_id, category)
once_received <- all_received[!duplicated(all_received$subitem_id),]

repeat_received <- all_received %>% group_by(subitem_id) %>% summarize(count = n())
repeat_received <- merge(repeat_received, once_received, by = "subitem_id")
repeat_received <- repeat_received %>% 
                     filter(count > 1) %>% 
                     group_by(category) %>% 
                     summarize(count = n())

ggplot(repeat_received, aes(x = category, y = count)) + geom_bar(fill = "#43ad26", stat = "identity") + labs(title = "Which category is most re-received?")

# CHAIRS ARE RE-RECEIVED MOST OFTEN -- COMPARE THIS TO SOLD COUNT (IN THE BEGINNING) 
```
